/**
 * County Data for Court Filing Templates
 *
 * County option arrays for jurisdiction-specific caption inputs.
 * Each array is sorted alphabetically and formatted as select options
 * where the value is the county name used directly in document captions
 * (e.g., "COUNTY OF LOS ANGELES").
 */

// ============================================================================
// California Counties (58)
// ============================================================================

export const CA_COUNTIES: { value: string; label: string }[] = [
  { value: "Alameda", label: "Alameda" },
  { value: "Alpine", label: "Alpine" },
  { value: "Amador", label: "Amador" },
  { value: "Butte", label: "Butte" },
  { value: "Calaveras", label: "Calaveras" },
  { value: "Colusa", label: "Colusa" },
  { value: "Contra Costa", label: "Contra Costa" },
  { value: "Del Norte", label: "Del Norte" },
  { value: "El Dorado", label: "El Dorado" },
  { value: "Fresno", label: "Fresno" },
  { value: "Glenn", label: "Glenn" },
  { value: "Humboldt", label: "Humboldt" },
  { value: "Imperial", label: "Imperial" },
  { value: "Inyo", label: "Inyo" },
  { value: "Kern", label: "Kern" },
  { value: "Kings", label: "Kings" },
  { value: "Lake", label: "Lake" },
  { value: "Lassen", label: "Lassen" },
  { value: "Los Angeles", label: "Los Angeles" },
  { value: "Madera", label: "Madera" },
  { value: "Marin", label: "Marin" },
  { value: "Mariposa", label: "Mariposa" },
  { value: "Mendocino", label: "Mendocino" },
  { value: "Merced", label: "Merced" },
  { value: "Modoc", label: "Modoc" },
  { value: "Mono", label: "Mono" },
  { value: "Monterey", label: "Monterey" },
  { value: "Napa", label: "Napa" },
  { value: "Nevada", label: "Nevada" },
  { value: "Orange", label: "Orange" },
  { value: "Placer", label: "Placer" },
  { value: "Plumas", label: "Plumas" },
  { value: "Riverside", label: "Riverside" },
  { value: "Sacramento", label: "Sacramento" },
  { value: "San Benito", label: "San Benito" },
  { value: "San Bernardino", label: "San Bernardino" },
  { value: "San Diego", label: "San Diego" },
  { value: "San Francisco", label: "San Francisco" },
  { value: "San Joaquin", label: "San Joaquin" },
  { value: "San Luis Obispo", label: "San Luis Obispo" },
  { value: "San Mateo", label: "San Mateo" },
  { value: "Santa Barbara", label: "Santa Barbara" },
  { value: "Santa Clara", label: "Santa Clara" },
  { value: "Santa Cruz", label: "Santa Cruz" },
  { value: "Shasta", label: "Shasta" },
  { value: "Sierra", label: "Sierra" },
  { value: "Siskiyou", label: "Siskiyou" },
  { value: "Solano", label: "Solano" },
  { value: "Sonoma", label: "Sonoma" },
  { value: "Stanislaus", label: "Stanislaus" },
  { value: "Sutter", label: "Sutter" },
  { value: "Tehama", label: "Tehama" },
  { value: "Trinity", label: "Trinity" },
  { value: "Tulare", label: "Tulare" },
  { value: "Tuolumne", label: "Tuolumne" },
  { value: "Ventura", label: "Ventura" },
  { value: "Yolo", label: "Yolo" },
  { value: "Yuba", label: "Yuba" },
  { value: "other", label: "Other" },
];

// ============================================================================
// New York Counties (62)
// ============================================================================

export const NY_COUNTIES: { value: string; label: string }[] = [
  { value: "Albany", label: "Albany" },
  { value: "Allegany", label: "Allegany" },
  { value: "Bronx", label: "Bronx" },
  { value: "Broome", label: "Broome" },
  { value: "Cattaraugus", label: "Cattaraugus" },
  { value: "Cayuga", label: "Cayuga" },
  { value: "Chautauqua", label: "Chautauqua" },
  { value: "Chemung", label: "Chemung" },
  { value: "Chenango", label: "Chenango" },
  { value: "Clinton", label: "Clinton" },
  { value: "Columbia", label: "Columbia" },
  { value: "Cortland", label: "Cortland" },
  { value: "Delaware", label: "Delaware" },
  { value: "Dutchess", label: "Dutchess" },
  { value: "Erie", label: "Erie" },
  { value: "Essex", label: "Essex" },
  { value: "Franklin", label: "Franklin" },
  { value: "Fulton", label: "Fulton" },
  { value: "Genesee", label: "Genesee" },
  { value: "Greene", label: "Greene" },
  { value: "Hamilton", label: "Hamilton" },
  { value: "Herkimer", label: "Herkimer" },
  { value: "Jefferson", label: "Jefferson" },
  { value: "Kings", label: "Kings (Brooklyn)" },
  { value: "Lewis", label: "Lewis" },
  { value: "Livingston", label: "Livingston" },
  { value: "Madison", label: "Madison" },
  { value: "Monroe", label: "Monroe" },
  { value: "Montgomery", label: "Montgomery" },
  { value: "Nassau", label: "Nassau" },
  { value: "New York", label: "New York (Manhattan)" },
  { value: "Niagara", label: "Niagara" },
  { value: "Oneida", label: "Oneida" },
  { value: "Onondaga", label: "Onondaga" },
  { value: "Ontario", label: "Ontario" },
  { value: "Orange", label: "Orange" },
  { value: "Orleans", label: "Orleans" },
  { value: "Oswego", label: "Oswego" },
  { value: "Otsego", label: "Otsego" },
  { value: "Putnam", label: "Putnam" },
  { value: "Queens", label: "Queens" },
  { value: "Rensselaer", label: "Rensselaer" },
  { value: "Richmond", label: "Richmond (Staten Island)" },
  { value: "Rockland", label: "Rockland" },
  { value: "Saratoga", label: "Saratoga" },
  { value: "Schenectady", label: "Schenectady" },
  { value: "Schoharie", label: "Schoharie" },
  { value: "Schuyler", label: "Schuyler" },
  { value: "Seneca", label: "Seneca" },
  { value: "St. Lawrence", label: "St. Lawrence" },
  { value: "Steuben", label: "Steuben" },
  { value: "Suffolk", label: "Suffolk" },
  { value: "Sullivan", label: "Sullivan" },
  { value: "Tioga", label: "Tioga" },
  { value: "Tompkins", label: "Tompkins" },
  { value: "Ulster", label: "Ulster" },
  { value: "Warren", label: "Warren" },
  { value: "Washington", label: "Washington" },
  { value: "Wayne", label: "Wayne" },
  { value: "Westchester", label: "Westchester" },
  { value: "Wyoming", label: "Wyoming" },
  { value: "Yates", label: "Yates" },
  { value: "other", label: "Other" },
];
