/**
 * County Data for Court Filing Templates
 *
 * County option arrays for jurisdiction-specific caption inputs.
 * Each array is sorted alphabetically and formatted as select options
 * where the value is the county name used directly in document captions
 * (e.g., "COUNTY OF LOS ANGELES").
 */

// ============================================================================
// California Counties (58)
// ============================================================================

export const CA_COUNTIES: { value: string; label: string }[] = [
  { value: "Alameda", label: "Alameda" },
  { value: "Alpine", label: "Alpine" },
  { value: "Amador", label: "Amador" },
  { value: "Butte", label: "Butte" },
  { value: "Calaveras", label: "Calaveras" },
  { value: "Colusa", label: "Colusa" },
  { value: "Contra Costa", label: "Contra Costa" },
  { value: "Del Norte", label: "Del Norte" },
  { value: "El Dorado", label: "El Dorado" },
  { value: "Fresno", label: "Fresno" },
  { value: "Glenn", label: "Glenn" },
  { value: "Humboldt", label: "Humboldt" },
  { value: "Imperial", label: "Imperial" },
  { value: "Inyo", label: "Inyo" },
  { value: "Kern", label: "Kern" },
  { value: "Kings", label: "Kings" },
  { value: "Lake", label: "Lake" },
  { value: "Lassen", label: "Lassen" },
  { value: "Los Angeles", label: "Los Angeles" },
  { value: "Madera", label: "Madera" },
  { value: "Marin", label: "Marin" },
  { value: "Mariposa", label: "Mariposa" },
  { value: "Mendocino", label: "Mendocino" },
  { value: "Merced", label: "Merced" },
  { value: "Modoc", label: "Modoc" },
  { value: "Mono", label: "Mono" },
  { value: "Monterey", label: "Monterey" },
  { value: "Napa", label: "Napa" },
  { value: "Nevada", label: "Nevada" },
  { value: "Orange", label: "Orange" },
  { value: "Placer", label: "Placer" },
  { value: "Plumas", label: "Plumas" },
  { value: "Riverside", label: "Riverside" },
  { value: "Sacramento", label: "Sacramento" },
  { value: "San Benito", label: "San Benito" },
  { value: "San Bernardino", label: "San Bernardino" },
  { value: "San Diego", label: "San Diego" },
  { value: "San Francisco", label: "San Francisco" },
  { value: "San Joaquin", label: "San Joaquin" },
  { value: "San Luis Obispo", label: "San Luis Obispo" },
  { value: "San Mateo", label: "San Mateo" },
  { value: "Santa Barbara", label: "Santa Barbara" },
  { value: "Santa Clara", label: "Santa Clara" },
  { value: "Santa Cruz", label: "Santa Cruz" },
  { value: "Shasta", label: "Shasta" },
  { value: "Sierra", label: "Sierra" },
  { value: "Siskiyou", label: "Siskiyou" },
  { value: "Solano", label: "Solano" },
  { value: "Sonoma", label: "Sonoma" },
  { value: "Stanislaus", label: "Stanislaus" },
  { value: "Sutter", label: "Sutter" },
  { value: "Tehama", label: "Tehama" },
  { value: "Trinity", label: "Trinity" },
  { value: "Tulare", label: "Tulare" },
  { value: "Tuolumne", label: "Tuolumne" },
  { value: "Ventura", label: "Ventura" },
  { value: "Yolo", label: "Yolo" },
  { value: "Yuba", label: "Yuba" },
  { value: "other", label: "Other" },
];

// ============================================================================
// New York Counties (62)
// ============================================================================

export const NY_COUNTIES: { value: string; label: string }[] = [
  { value: "Albany", label: "Albany" },
  { value: "Allegany", label: "Allegany" },
  { value: "Bronx", label: "Bronx" },
  { value: "Broome", label: "Broome" },
  { value: "Cattaraugus", label: "Cattaraugus" },
  { value: "Cayuga", label: "Cayuga" },
  { value: "Chautauqua", label: "Chautauqua" },
  { value: "Chemung", label: "Chemung" },
  { value: "Chenango", label: "Chenango" },
  { value: "Clinton", label: "Clinton" },
  { value: "Columbia", label: "Columbia" },
  { value: "Cortland", label: "Cortland" },
  { value: "Delaware", label: "Delaware" },
  { value: "Dutchess", label: "Dutchess" },
  { value: "Erie", label: "Erie" },
  { value: "Essex", label: "Essex" },
  { value: "Franklin", label: "Franklin" },
  { value: "Fulton", label: "Fulton" },
  { value: "Genesee", label: "Genesee" },
  { value: "Greene", label: "Greene" },
  { value: "Hamilton", label: "Hamilton" },
  { value: "Herkimer", label: "Herkimer" },
  { value: "Jefferson", label: "Jefferson" },
  { value: "Kings", label: "Kings (Brooklyn)" },
  { value: "Lewis", label: "Lewis" },
  { value: "Livingston", label: "Livingston" },
  { value: "Madison", label: "Madison" },
  { value: "Monroe", label: "Monroe" },
  { value: "Montgomery", label: "Montgomery" },
  { value: "Nassau", label: "Nassau" },
  { value: "New York", label: "New York (Manhattan)" },
  { value: "Niagara", label: "Niagara" },
  { value: "Oneida", label: "Oneida" },
  { value: "Onondaga", label: "Onondaga" },
  { value: "Ontario", label: "Ontario" },
  { value: "Orange", label: "Orange" },
  { value: "Orleans", label: "Orleans" },
  { value: "Oswego", label: "Oswego" },
  { value: "Otsego", label: "Otsego" },
  { value: "Putnam", label: "Putnam" },
  { value: "Queens", label: "Queens" },
  { value: "Rensselaer", label: "Rensselaer" },
  { value: "Richmond", label: "Richmond (Staten Island)" },
  { value: "Rockland", label: "Rockland" },
  { value: "Saratoga", label: "Saratoga" },
  { value: "Schenectady", label: "Schenectady" },
  { value: "Schoharie", label: "Schoharie" },
  { value: "Schuyler", label: "Schuyler" },
  { value: "Seneca", label: "Seneca" },
  { value: "St. Lawrence", label: "St. Lawrence" },
  { value: "Steuben", label: "Steuben" },
  { value: "Suffolk", label: "Suffolk" },
  { value: "Sullivan", label: "Sullivan" },
  { value: "Tioga", label: "Tioga" },
  { value: "Tompkins", label: "Tompkins" },
  { value: "Ulster", label: "Ulster" },
  { value: "Warren", label: "Warren" },
  { value: "Washington", label: "Washington" },
  { value: "Wayne", label: "Wayne" },
  { value: "Westchester", label: "Westchester" },
  { value: "Wyoming", label: "Wyoming" },
  { value: "Yates", label: "Yates" },
  { value: "other", label: "Other" },
];

// ============================================================================
// Texas Counties (254)
// ============================================================================

export const TX_COUNTIES: { value: string; label: string }[] = [
  { value: "Anderson", label: "Anderson" },
  { value: "Andrews", label: "Andrews" },
  { value: "Angelina", label: "Angelina" },
  { value: "Aransas", label: "Aransas" },
  { value: "Archer", label: "Archer" },
  { value: "Armstrong", label: "Armstrong" },
  { value: "Atascosa", label: "Atascosa" },
  { value: "Austin", label: "Austin" },
  { value: "Bailey", label: "Bailey" },
  { value: "Bandera", label: "Bandera" },
  { value: "Bastrop", label: "Bastrop" },
  { value: "Baylor", label: "Baylor" },
  { value: "Bee", label: "Bee" },
  { value: "Bell", label: "Bell" },
  { value: "Bexar", label: "Bexar" },
  { value: "Blanco", label: "Blanco" },
  { value: "Borden", label: "Borden" },
  { value: "Bosque", label: "Bosque" },
  { value: "Bowie", label: "Bowie" },
  { value: "Brazoria", label: "Brazoria" },
  { value: "Brazos", label: "Brazos" },
  { value: "Brewster", label: "Brewster" },
  { value: "Briscoe", label: "Briscoe" },
  { value: "Brooks", label: "Brooks" },
  { value: "Brown", label: "Brown" },
  { value: "Burleson", label: "Burleson" },
  { value: "Burnet", label: "Burnet" },
  { value: "Caldwell", label: "Caldwell" },
  { value: "Calhoun", label: "Calhoun" },
  { value: "Callahan", label: "Callahan" },
  { value: "Cameron", label: "Cameron" },
  { value: "Camp", label: "Camp" },
  { value: "Carson", label: "Carson" },
  { value: "Cass", label: "Cass" },
  { value: "Castro", label: "Castro" },
  { value: "Chambers", label: "Chambers" },
  { value: "Cherokee", label: "Cherokee" },
  { value: "Childress", label: "Childress" },
  { value: "Clay", label: "Clay" },
  { value: "Cochran", label: "Cochran" },
  { value: "Coke", label: "Coke" },
  { value: "Coleman", label: "Coleman" },
  { value: "Collin", label: "Collin" },
  { value: "Collingsworth", label: "Collingsworth" },
  { value: "Colorado", label: "Colorado" },
  { value: "Comal", label: "Comal" },
  { value: "Comanche", label: "Comanche" },
  { value: "Concho", label: "Concho" },
  { value: "Cooke", label: "Cooke" },
  { value: "Coryell", label: "Coryell" },
  { value: "Cottle", label: "Cottle" },
  { value: "Crane", label: "Crane" },
  { value: "Crockett", label: "Crockett" },
  { value: "Crosby", label: "Crosby" },
  { value: "Culberson", label: "Culberson" },
  { value: "Dallam", label: "Dallam" },
  { value: "Dallas", label: "Dallas" },
  { value: "Dawson", label: "Dawson" },
  { value: "Deaf Smith", label: "Deaf Smith" },
  { value: "Delta", label: "Delta" },
  { value: "Denton", label: "Denton" },
  { value: "DeWitt", label: "DeWitt" },
  { value: "Dickens", label: "Dickens" },
  { value: "Dimmit", label: "Dimmit" },
  { value: "Donley", label: "Donley" },
  { value: "Duval", label: "Duval" },
  { value: "Eastland", label: "Eastland" },
  { value: "Ector", label: "Ector" },
  { value: "Edwards", label: "Edwards" },
  { value: "El Paso", label: "El Paso" },
  { value: "Ellis", label: "Ellis" },
  { value: "Erath", label: "Erath" },
  { value: "Falls", label: "Falls" },
  { value: "Fannin", label: "Fannin" },
  { value: "Fayette", label: "Fayette" },
  { value: "Fisher", label: "Fisher" },
  { value: "Floyd", label: "Floyd" },
  { value: "Foard", label: "Foard" },
  { value: "Fort Bend", label: "Fort Bend" },
  { value: "Franklin", label: "Franklin" },
  { value: "Freestone", label: "Freestone" },
  { value: "Frio", label: "Frio" },
  { value: "Gaines", label: "Gaines" },
  { value: "Galveston", label: "Galveston" },
  { value: "Garza", label: "Garza" },
  { value: "Gillespie", label: "Gillespie" },
  { value: "Glasscock", label: "Glasscock" },
  { value: "Goliad", label: "Goliad" },
  { value: "Gonzales", label: "Gonzales" },
  { value: "Gray", label: "Gray" },
  { value: "Grayson", label: "Grayson" },
  { value: "Gregg", label: "Gregg" },
  { value: "Grimes", label: "Grimes" },
  { value: "Guadalupe", label: "Guadalupe" },
  { value: "Hale", label: "Hale" },
  { value: "Hall", label: "Hall" },
  { value: "Hamilton", label: "Hamilton" },
  { value: "Hansford", label: "Hansford" },
  { value: "Hardeman", label: "Hardeman" },
  { value: "Hardin", label: "Hardin" },
  { value: "Harris", label: "Harris" },
  { value: "Harrison", label: "Harrison" },
  { value: "Hartley", label: "Hartley" },
  { value: "Haskell", label: "Haskell" },
  { value: "Hays", label: "Hays" },
  { value: "Hemphill", label: "Hemphill" },
  { value: "Henderson", label: "Henderson" },
  { value: "Hidalgo", label: "Hidalgo" },
  { value: "Hill", label: "Hill" },
  { value: "Hockley", label: "Hockley" },
  { value: "Hood", label: "Hood" },
  { value: "Hopkins", label: "Hopkins" },
  { value: "Houston", label: "Houston" },
  { value: "Howard", label: "Howard" },
  { value: "Hudspeth", label: "Hudspeth" },
  { value: "Hunt", label: "Hunt" },
  { value: "Hutchinson", label: "Hutchinson" },
  { value: "Irion", label: "Irion" },
  { value: "Jack", label: "Jack" },
  { value: "Jackson", label: "Jackson" },
  { value: "Jasper", label: "Jasper" },
  { value: "Jeff Davis", label: "Jeff Davis" },
  { value: "Jefferson", label: "Jefferson" },
  { value: "Jim Hogg", label: "Jim Hogg" },
  { value: "Jim Wells", label: "Jim Wells" },
  { value: "Johnson", label: "Johnson" },
  { value: "Jones", label: "Jones" },
  { value: "Karnes", label: "Karnes" },
  { value: "Kaufman", label: "Kaufman" },
  { value: "Kendall", label: "Kendall" },
  { value: "Kenedy", label: "Kenedy" },
  { value: "Kent", label: "Kent" },
  { value: "Kerr", label: "Kerr" },
  { value: "Kimble", label: "Kimble" },
  { value: "King", label: "King" },
  { value: "Kinney", label: "Kinney" },
  { value: "Kleberg", label: "Kleberg" },
  { value: "Knox", label: "Knox" },
  { value: "La Salle", label: "La Salle" },
  { value: "Lamar", label: "Lamar" },
  { value: "Lamb", label: "Lamb" },
  { value: "Lampasas", label: "Lampasas" },
  { value: "Lavaca", label: "Lavaca" },
  { value: "Lee", label: "Lee" },
  { value: "Leon", label: "Leon" },
  { value: "Liberty", label: "Liberty" },
  { value: "Limestone", label: "Limestone" },
  { value: "Lipscomb", label: "Lipscomb" },
  { value: "Live Oak", label: "Live Oak" },
  { value: "Llano", label: "Llano" },
  { value: "Loving", label: "Loving" },
  { value: "Lubbock", label: "Lubbock" },
  { value: "Lynn", label: "Lynn" },
  { value: "Madison", label: "Madison" },
  { value: "Marion", label: "Marion" },
  { value: "Martin", label: "Martin" },
  { value: "Mason", label: "Mason" },
  { value: "Matagorda", label: "Matagorda" },
  { value: "Maverick", label: "Maverick" },
  { value: "McCulloch", label: "McCulloch" },
  { value: "McLennan", label: "McLennan" },
  { value: "McMullen", label: "McMullen" },
  { value: "Medina", label: "Medina" },
  { value: "Menard", label: "Menard" },
  { value: "Midland", label: "Midland" },
  { value: "Milam", label: "Milam" },
  { value: "Mills", label: "Mills" },
  { value: "Mitchell", label: "Mitchell" },
  { value: "Montague", label: "Montague" },
  { value: "Montgomery", label: "Montgomery" },
  { value: "Moore", label: "Moore" },
  { value: "Morris", label: "Morris" },
  { value: "Motley", label: "Motley" },
  { value: "Nacogdoches", label: "Nacogdoches" },
  { value: "Navarro", label: "Navarro" },
  { value: "Newton", label: "Newton" },
  { value: "Nolan", label: "Nolan" },
  { value: "Nueces", label: "Nueces" },
  { value: "Ochiltree", label: "Ochiltree" },
  { value: "Oldham", label: "Oldham" },
  { value: "Orange", label: "Orange" },
  { value: "Palo Pinto", label: "Palo Pinto" },
  { value: "Panola", label: "Panola" },
  { value: "Parker", label: "Parker" },
  { value: "Parmer", label: "Parmer" },
  { value: "Pecos", label: "Pecos" },
  { value: "Polk", label: "Polk" },
  { value: "Potter", label: "Potter" },
  { value: "Presidio", label: "Presidio" },
  { value: "Rains", label: "Rains" },
  { value: "Randall", label: "Randall" },
  { value: "Reagan", label: "Reagan" },
  { value: "Real", label: "Real" },
  { value: "Red River", label: "Red River" },
  { value: "Reeves", label: "Reeves" },
  { value: "Refugio", label: "Refugio" },
  { value: "Roberts", label: "Roberts" },
  { value: "Robertson", label: "Robertson" },
  { value: "Rockwall", label: "Rockwall" },
  { value: "Runnels", label: "Runnels" },
  { value: "Rusk", label: "Rusk" },
  { value: "Sabine", label: "Sabine" },
  { value: "San Augustine", label: "San Augustine" },
  { value: "San Jacinto", label: "San Jacinto" },
  { value: "San Patricio", label: "San Patricio" },
  { value: "San Saba", label: "San Saba" },
  { value: "Schleicher", label: "Schleicher" },
  { value: "Scurry", label: "Scurry" },
  { value: "Shackelford", label: "Shackelford" },
  { value: "Shelby", label: "Shelby" },
  { value: "Sherman", label: "Sherman" },
  { value: "Smith", label: "Smith" },
  { value: "Somervell", label: "Somervell" },
  { value: "Starr", label: "Starr" },
  { value: "Stephens", label: "Stephens" },
  { value: "Sterling", label: "Sterling" },
  { value: "Stonewall", label: "Stonewall" },
  { value: "Sutton", label: "Sutton" },
  { value: "Swisher", label: "Swisher" },
  { value: "Tarrant", label: "Tarrant" },
  { value: "Taylor", label: "Taylor" },
  { value: "Terrell", label: "Terrell" },
  { value: "Terry", label: "Terry" },
  { value: "Throckmorton", label: "Throckmorton" },
  { value: "Titus", label: "Titus" },
  { value: "Tom Green", label: "Tom Green" },
  { value: "Travis", label: "Travis" },
  { value: "Trinity", label: "Trinity" },
  { value: "Tyler", label: "Tyler" },
  { value: "Upshur", label: "Upshur" },
  { value: "Upton", label: "Upton" },
  { value: "Uvalde", label: "Uvalde" },
  { value: "Val Verde", label: "Val Verde" },
  { value: "Van Zandt", label: "Van Zandt" },
  { value: "Victoria", label: "Victoria" },
  { value: "Walker", label: "Walker" },
  { value: "Waller", label: "Waller" },
  { value: "Ward", label: "Ward" },
  { value: "Washington", label: "Washington" },
  { value: "Webb", label: "Webb" },
  { value: "Wharton", label: "Wharton" },
  { value: "Wheeler", label: "Wheeler" },
  { value: "Wichita", label: "Wichita" },
  { value: "Wilbarger", label: "Wilbarger" },
  { value: "Willacy", label: "Willacy" },
  { value: "Williamson", label: "Williamson" },
  { value: "Wilson", label: "Wilson" },
  { value: "Winkler", label: "Winkler" },
  { value: "Wise", label: "Wise" },
  { value: "Wood", label: "Wood" },
  { value: "Yoakum", label: "Yoakum" },
  { value: "Young", label: "Young" },
  { value: "Zapata", label: "Zapata" },
  { value: "Zavala", label: "Zavala" },
  { value: "other", label: "Other" },
];
