/**
 * Content Review Report Generator
 *
 * Reads JSON output files from review-content.ts and creates a GitHub Issue
 * with all suggested edits, organized by category and severity.
 *
 * Run: npx tsx scripts/content-review/generate-report.ts
 * Env: GITHUB_TOKEN, GITHUB_REPOSITORY
 */

import fs from "fs";
import path from "path";

// ─── Types ────────────────────────────────────────────────────────────────────

interface Suggestion {
  file: string;
  section: string;
  currentText: string;
  proposedText: string;
  reason: string;
  severity: "low" | "medium" | "high";
}

interface FileReviewResult {
  file: string;
  suggestions: Suggestion[];
  reviewedAt: string;
  error?: string;
}

interface CategoryOutput {
  category: string;
  reviewedAt: string;
  files: FileReviewResult[];
  totalSuggestions: number;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const OUTPUT_DIR = path.join(import.meta.dirname, "output");

const DIFF_FILES = [
  "guidance-diff.json",
  "immigration-diff.json",
  "support-diff.json",
  "resources-diff.json",
];

const SEVERITY_EMOJI: Record<string, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🔵",
};

function getQuarter(): string {
  const now = new Date();
  const q = Math.ceil((now.getMonth() + 1) / 3);
  return `Q${q} ${now.getFullYear()}`;
}

function renderSuggestion(s: Suggestion, index: number): string {
  return `
<details>
<summary>${SEVERITY_EMOJI[s.severity]} <strong>${s.section}</strong> — <code>${s.file}</code></summary>

**Current text:**
> ${s.currentText}

**Proposed replacement:**
> ${s.proposedText}

**Reason:** ${s.reason}

**Severity:** ${s.severity.toUpperCase()}

</details>`.trim();
}

function renderCategory(data: CategoryOutput): string {
  const allSuggestions = data.files.flatMap((f) => f.suggestions);
  const errors = data.files.filter((f) => f.error);

  if (allSuggestions.length === 0 && errors.length === 0) {
    return `### ✅ ${data.category}\n\nNo issues found — content looks current and accurate.\n`;
  }

  const high = allSuggestions.filter((s) => s.severity === "high");
  const medium = allSuggestions.filter((s) => s.severity === "medium");
  const low = allSuggestions.filter((s) => s.severity === "low");

  let out = `### ${data.category}\n\n`;
  out += `**${allSuggestions.length} suggestion(s):** 🔴 ${high.length} high · 🟡 ${medium.length} medium · 🔵 ${low.length} low\n\n`;

  // High severity first
  if (high.length > 0) {
    out += `#### 🔴 High Priority (review immediately)\n\n`;
    high.forEach((s, i) => { out += renderSuggestion(s, i) + "\n\n"; });
  }
  if (medium.length > 0) {
    out += `#### 🟡 Medium Priority\n\n`;
    medium.forEach((s, i) => { out += renderSuggestion(s, i) + "\n\n"; });
  }
  if (low.length > 0) {
    out += `#### 🔵 Low Priority (clarity improvements)\n\n`;
    low.forEach((s, i) => { out += renderSuggestion(s, i) + "\n\n"; });
  }

  if (errors.length > 0) {
    out += `#### ⚠️ Files with errors\n\n`;
    errors.forEach((f) => { out += `- \`${f.file}\`: ${f.error}\n`; });
    out += "\n";
  }

  return out;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const quarter = getQuarter();

  // Load all available diff files
  const categories: CategoryOutput[] = [];
  for (const file of DIFF_FILES) {
    const fullPath = path.join(OUTPUT_DIR, file);
    if (fs.existsSync(fullPath)) {
      try {
        const data = JSON.parse(fs.readFileSync(fullPath, "utf-8")) as CategoryOutput;
        categories.push(data);
      } catch (err) {
        console.warn(`Could not parse ${file}:`, err);
      }
    } else {
      console.warn(`Output file not found (category may have been skipped): ${file}`);
    }
  }

  if (categories.length === 0) {
    console.error("No diff files found. Run review-content.ts first.");
    process.exit(1);
  }

  const totalSuggestions = categories.reduce((sum, c) => sum + c.totalSuggestions, 0);
  const filesReviewed = categories.reduce((sum, c) => sum + c.files.length, 0);
  const reviewDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Build issue body
  let body = `## Quarterly Content Review — ${quarter}

**Review date:** ${reviewDate}
**Files reviewed:** ${filesReviewed}
**Total suggestions:** ${totalSuggestions}

This issue was automatically generated by the quarterly content review workflow. Each suggestion below was produced by Claude AI reviewing user-facing text for legal accuracy, currency, and clarity.

> **How to use this issue:** Review each suggestion, apply changes you agree with directly in the relevant file, and close this issue when done. Dismiss suggestions you disagree with by leaving a comment explaining why.

---

`;

  for (const cat of categories) {
    body += renderCategory(cat) + "\n---\n\n";
  }

  body += `\n*Generated by [quarterly-content-review workflow](https://github.com/${process.env.GITHUB_REPOSITORY}/actions)*`;

  // Create GitHub Issue via REST API
  const [owner, repo] = (process.env.GITHUB_REPOSITORY || "").split("/");
  if (!owner || !repo) {
    // Running locally — just print the body
    console.log("\n─── Issue body preview ───\n");
    console.log(body);
    return;
  }

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: `Quarterly Content Review — ${quarter}`,
      body,
      labels: ["content-review", "automated"],
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    console.error(`Failed to create GitHub issue: ${response.status} ${text}`);
    process.exit(1);
  }

  const issue = (await response.json()) as { html_url: string; number: number };
  console.log(`✅ GitHub Issue #${issue.number} created: ${issue.html_url}`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
