export interface AssistanceOrg {
  name: string;
  url: string;
  description: string;
}

export interface CourtFeeProfile {
  stateCode: string;
  stateName: string;
  filingFee: string;
  probationFee: string;
  publicDefenderFee: string;
  fineRange: string;
  surcharges: string;
  waiverForm: string;
  waiverIncome: string;
  assistanceOrgs: AssistanceOrg[];
}

export const NATIONAL_ASSISTANCE_ORGS: AssistanceOrg[] = [
  {
    name: "Fines & Fees Justice Center",
    url: "https://finesandfeesjusticecenter.org",
    description: "State-by-state legal aid referrals and policy resources on court fines and fees",
  },
  {
    name: "The Bail Project",
    url: "https://bailproject.org",
    description: "Emergency bail assistance and reentry support for people who cannot afford bail",
  },
  {
    name: "Legal Services Corporation",
    url: "https://www.lsc.gov",
    description: "Federally-funded civil legal aid for income-eligible individuals and families",
  },
  {
    name: "211.org",
    url: "https://www.211.org",
    description: "Local emergency financial assistance by ZIP code — call or text 211",
  },
  {
    name: "JustLeadershipUSA",
    url: "https://jlusa.org",
    description: "Advocacy and direct assistance for justice-involved individuals and families",
  },
];

export const courtFeesByState: Record<string, CourtFeeProfile> = {
  AL: {
    stateCode: "AL",
    stateName: "Alabama",
    filingFee: "$30–$300",
    probationFee: "$40–$80/month",
    publicDefenderFee: "$0–$50 application fee",
    fineRange: "Misdemeanor: up to $6,000 · Felony: up to $60,000",
    surcharges: "Penalty assessments add ~175% on top of base fines",
    waiverForm: "Form Affidavit of Substantial Hardship (C-10)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Alabama Appleseed Center",
        url: "https://alabamaappleseed.org",
        description: "Legal advocacy and resources for Alabamians facing poverty and injustice",
      },
    ],
  },
  AK: {
    stateCode: "AK",
    stateName: "Alaska",
    filingFee: "$30–$150",
    probationFee: "$0–$60/month (varies by supervision level)",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $25,000 · Felony: up to $500,000",
    surcharges: "Surcharges add approximately 75–100% on top of base fines",
    waiverForm: "Application for Waiver of Fees (TF-920)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Alaska Legal Services Corporation",
        url: "https://www.alsc-law.org",
        description: "Free civil legal help for low-income Alaskans",
      },
    ],
  },
  AZ: {
    stateCode: "AZ",
    stateName: "Arizona",
    filingFee: "$60–$300",
    probationFee: "$50–$65/month",
    publicDefenderFee: "$0–$25 application fee",
    fineRange: "Misdemeanor: up to $2,500 · Felony: up to $150,000",
    surcharges: "Penalty assessments add 83% on top of base fines (state + county)",
    waiverForm: "Petition for Deferral/Waiver of Court Fees (Form 1)",
    waiverIncome: "Income ≤150% federal poverty level",
    assistanceOrgs: [
      {
        name: "Community Legal Services (AZ)",
        url: "https://clsaz.org",
        description: "Free legal aid for low-income residents of Maricopa County",
      },
      {
        name: "Southern Arizona Legal Aid",
        url: "https://www.sazlegalaid.org",
        description: "Free civil legal services for low-income Arizonans",
      },
    ],
  },
  AR: {
    stateCode: "AR",
    stateName: "Arkansas",
    filingFee: "$50–$200",
    probationFee: "$35–$50/month",
    publicDefenderFee: "$0–$50 application fee",
    fineRange: "Misdemeanor: up to $2,500 · Felony: up to $15,000",
    surcharges: "City and county assessments add 50–100% on base fines",
    waiverForm: "Affidavit of Inability to Pay (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Center for Arkansas Legal Services",
        url: "https://arlegalservices.org",
        description: "Free civil legal assistance for qualifying Arkansans",
      },
    ],
  },
  CA: {
    stateCode: "CA",
    stateName: "California",
    filingFee: "$30–$435",
    probationFee: "$0–$120/month (waived for low-income since 2021 AB 1869)",
    publicDefenderFee: "$0 (application fees eliminated statewide)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $10,000",
    surcharges: "State penalty assessments add approximately 390% on top of base fines",
    waiverForm: "Request to Waive Court Fees (Form FW-001)",
    waiverIncome: "Income ≤125% federal poverty level (or on public benefits)",
    assistanceOrgs: [
      {
        name: "Lawyers' Committee for Civil Rights (CA)",
        url: "https://www.lccrsf.org",
        description: "Advocacy and legal aid for Bay Area residents impacted by the justice system",
      },
      {
        name: "Debt Free Justice California",
        url: "https://debtfreejusticeca.org",
        description: "Resources and advocacy for eliminating criminal legal debt in California",
      },
    ],
  },
  CO: {
    stateCode: "CO",
    stateName: "Colorado",
    filingFee: "$50–$224",
    probationFee: "$50/month flat (community supervision)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $1,000,000",
    surcharges: "Surcharges add 37–75% on base fines",
    waiverForm: "Motion to Waive Fees — JDF 205",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Colorado Legal Services",
        url: "https://coloradolegalservices.org",
        description: "Free civil legal aid for low-income Coloradans",
      },
    ],
  },
  CT: {
    stateCode: "CT",
    stateName: "Connecticut",
    filingFee: "$50–$350",
    probationFee: "$0 (fees eliminated statewide)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $2,000 · Felony: up to $20,000",
    surcharges: "Offender-funded surcharges vary widely by charge type",
    waiverForm: "Application for Waiver of Fees (JD-FM-75)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Connecticut Legal Services",
        url: "https://ctlegalservices.org",
        description: "Free civil legal assistance for low-income Connecticut residents",
      },
    ],
  },
  DE: {
    stateCode: "DE",
    stateName: "Delaware",
    filingFee: "$25–$200",
    probationFee: "$20–$50/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $2,300 · Felony: up to $15,000",
    surcharges: "Victim compensation surcharges add 15–20% on base fines",
    waiverForm: "Petition for In Forma Pauperis (IFP — ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Delaware Volunteer Legal Services",
        url: "https://dvls.org",
        description: "Pro bono civil legal aid for low-income Delawareans",
      },
    ],
  },
  FL: {
    stateCode: "FL",
    stateName: "Florida",
    filingFee: "$50–$400",
    probationFee: "$50–$100/month",
    publicDefenderFee: "$50 application fee (waivable)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $10,000",
    surcharges: "County and state surcharges add 100–200% on base fines",
    waiverForm: "Application for Determination of Civil Indigent Status (Clerk Form)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Florida Legal Services",
        url: "https://floridalegal.org",
        description: "Statewide advocacy and legal aid referrals for low-income Floridians",
      },
      {
        name: "Three Rivers Legal Services",
        url: "https://trls.org",
        description: "Free civil legal aid for north Florida and Gainesville area",
      },
    ],
  },
  GA: {
    stateCode: "GA",
    stateName: "Georgia",
    filingFee: "$30–$250",
    probationFee: "$30–$50/month",
    publicDefenderFee: "$0 (no statewide application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $100,000",
    surcharges: "Penalty assessments add approximately 100–150% on base fines",
    waiverForm: "Affidavit of Indigence (ask court clerk for form)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Georgia Legal Services Program",
        url: "https://www.glsp.org",
        description: "Free civil legal aid for low-income rural and suburban Georgians",
      },
    ],
  },
  HI: {
    stateCode: "HI",
    stateName: "Hawaii",
    filingFee: "$30–$175",
    probationFee: "$0–$30/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $2,000 · Felony: up to $50,000",
    surcharges: "Criminal injuries compensation fund adds ~$105 per conviction",
    waiverForm: "Motion to Proceed IFP (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid Society of Hawaii",
        url: "https://www.legalaidhawaii.org",
        description: "Free civil legal services for low-income Hawaii residents",
      },
    ],
  },
  ID: {
    stateCode: "ID",
    stateName: "Idaho",
    filingFee: "$30–$221",
    probationFee: "$25–$60/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $50,000",
    surcharges: "Penalty assessments and surcharges add 50–100% on base fines",
    waiverForm: "Affidavit and Order for Waiver of Fees (Form CAO CrM 3-2)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Idaho Legal Aid Services",
        url: "https://www.idaholegalaid.org",
        description: "Free civil legal assistance for low-income Idahoans",
      },
    ],
  },
  IL: {
    stateCode: "IL",
    stateName: "Illinois",
    filingFee: "$50–$400",
    probationFee: "$0–$50/month (waived for low-income under recent reforms)",
    publicDefenderFee: "$0 (fees eliminated under 2021 SAFE-T Act)",
    fineRange: "Misdemeanor: up to $2,500 · Felony: up to $25,000",
    surcharges: "Surcharges and assessments add 100–200% on base fines",
    waiverForm: "Application for Waiver of Court Fees (Form CC-In-Pro-Se)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Illinois Legal Aid Online",
        url: "https://www.illinoislegalaid.org",
        description: "Free legal information, forms, and attorney referrals for Illinoisans",
      },
      {
        name: "Cabrini Green Legal Aid",
        url: "https://www.cgla.net",
        description: "Free legal services for justice-involved people in the Chicago area",
      },
    ],
  },
  IN: {
    stateCode: "IN",
    stateName: "Indiana",
    filingFee: "$40–$250",
    probationFee: "$20–$100/month",
    publicDefenderFee: "$0–$100 (court-ordered reimbursement at case end)",
    fineRange: "Misdemeanor: up to $10,000 · Felony: up to $10,000",
    surcharges: "Supplemental public defender fee and court costs add significant amounts",
    waiverForm: "Petition to Proceed as an Indigent Person (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Indiana Legal Services",
        url: "https://www.indianalegalservices.org",
        description: "Free civil legal help for low-income Hoosiers",
      },
    ],
  },
  IA: {
    stateCode: "IA",
    stateName: "Iowa",
    filingFee: "$50–$185",
    probationFee: "$30–$60/month",
    publicDefenderFee: "$0–$150 (reimbursement ordered at sentencing)",
    fineRange: "Misdemeanor: up to $6,250 · Felony: up to $100,000",
    surcharges: "Court debt surcharge adds 10% to unpaid balances",
    waiverForm: "Application for Court-Appointed Counsel and Fee Waiver",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Iowa Legal Aid",
        url: "https://www.iowalegalaid.org",
        description: "Free civil legal assistance for low-income Iowans",
      },
    ],
  },
  KS: {
    stateCode: "KS",
    stateName: "Kansas",
    filingFee: "$30–$195",
    probationFee: "$20–$40/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $2,500 · Felony: up to $500,000",
    surcharges: "Law enforcement training fund surcharge adds $5–$200 per conviction",
    waiverForm: "Motion to Proceed IFP / Fee Waiver (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Kansas Legal Services",
        url: "https://kansaslegalservices.org",
        description: "Free civil legal services and online resources for qualifying Kansans",
      },
    ],
  },
  KY: {
    stateCode: "KY",
    stateName: "Kentucky",
    filingFee: "$50–$175",
    probationFee: "$0–$30/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $500 · Felony: up to $10,000",
    surcharges: "Court costs and fees often exceed base fines for misdemeanors",
    waiverForm: "Motion to Proceed IFP — AOC Form (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid Network of Kentucky",
        url: "https://lanky.org",
        description: "Free civil legal assistance for low-income Kentuckians",
      },
    ],
  },
  LA: {
    stateCode: "LA",
    stateName: "Louisiana",
    filingFee: "$50–$300",
    probationFee: "$30–$100/month (including supervision and fees)",
    publicDefenderFee: "$0–$40 application fee",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $50,000",
    surcharges: "Multiple dedicated fund surcharges add 100–200% on base fines",
    waiverForm: "Pauper's Affidavit (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Southeast Louisiana Legal Services",
        url: "https://slls.org",
        description: "Free civil legal aid for low-income residents of Southeast Louisiana",
      },
    ],
  },
  ME: {
    stateCode: "ME",
    stateName: "Maine",
    filingFee: "$30–$150",
    probationFee: "$0 (supervision fees eliminated)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $2,000 · Felony: up to $50,000",
    surcharges: "Victim Compensation Fund surcharge adds $50–$400 per case",
    waiverForm: "Motion to Proceed Without Payment of Fees (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Pine Tree Legal Assistance",
        url: "https://www.ptla.org",
        description: "Free civil legal services for low-income Maine residents",
      },
    ],
  },
  MD: {
    stateCode: "MD",
    stateName: "Maryland",
    filingFee: "$30–$250",
    probationFee: "$50–$70/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $2,500 · Felony: no statutory maximum (judge-set)",
    surcharges: "Surcharges for drug testing, electronic monitoring, etc. add significantly",
    waiverForm: "Request for Waiver of Prepaid Costs (CC-DC-089)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Maryland Legal Aid",
        url: "https://www.mdlab.org",
        description: "Free civil legal aid for low-income Marylanders",
      },
    ],
  },
  MA: {
    stateCode: "MA",
    stateName: "Massachusetts",
    filingFee: "$50–$300",
    probationFee: "$0 (probation fees eliminated under 2018 reform)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $250,000",
    surcharges: "Victim-witness assessment adds $50–$10,000 depending on charge",
    waiverForm: "Affidavit of Indigency (MPC 301 / CJ-D 137A)",
    waiverIncome: "Income ≤125% federal poverty level (or on public assistance)",
    assistanceOrgs: [
      {
        name: "Greater Boston Legal Services",
        url: "https://www.gbls.org",
        description: "Free civil legal aid for low-income Greater Boston residents",
      },
      {
        name: "Mass Legal Help",
        url: "https://www.masslegalhelp.org",
        description: "Free legal information, forms, and referrals for Massachusetts residents",
      },
    ],
  },
  MI: {
    stateCode: "MI",
    stateName: "Michigan",
    filingFee: "$50–$400",
    probationFee: "$30–$135/month",
    publicDefenderFee: "$0–$75 reimbursement at sentencing",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $15,000",
    surcharges: "Crime victim fee, state cost, and other fees add $60–$250 per case",
    waiverForm: "Fee Waiver — MC 20 form",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Michigan Legal Help",
        url: "https://michiganlegalhelp.org",
        description: "Free legal self-help tools and attorney referrals for Michiganders",
      },
    ],
  },
  MN: {
    stateCode: "MN",
    stateName: "Minnesota",
    filingFee: "$75–$320",
    probationFee: "$0–$50/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $3,000 · Felony: up to $90,000",
    surcharges: "Surcharges and assessments add 20–50% on base fines",
    waiverForm: "In Forma Pauperis Application — Form CIV103",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Mid-Minnesota Legal Aid",
        url: "https://www.midmnlegal.org",
        description: "Free civil legal services for qualifying Minnesotans",
      },
    ],
  },
  MS: {
    stateCode: "MS",
    stateName: "Mississippi",
    filingFee: "$40–$200",
    probationFee: "$45–$90/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $10,000",
    surcharges: "Multiple fund surcharges add 100–200% on base fines",
    waiverForm: "Affidavit of Indigence (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Mississippi Center for Justice",
        url: "https://mscenterforjustice.org",
        description: "Advocacy and legal resources challenging unjust fines and fees in Mississippi",
      },
    ],
  },
  MO: {
    stateCode: "MO",
    stateName: "Missouri",
    filingFee: "$50–$400",
    probationFee: "$30–$60/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $2,000 · Felony: up to $10,000",
    surcharges: "Court costs add $100–$400 on top of base fines per case",
    waiverForm: "Motion to Proceed as a Poor Person (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Services of Eastern Missouri",
        url: "https://lsem.org",
        description: "Free civil legal aid for low-income residents of eastern Missouri",
      },
    ],
  },
  MT: {
    stateCode: "MT",
    stateName: "Montana",
    filingFee: "$30–$170",
    probationFee: "$0–$30/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $50,000",
    surcharges: "Surcharges add approximately 50–75% on base fines",
    waiverForm: "Motion to Proceed IFP (ask court clerk for local form)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Montana Legal Services Association",
        url: "https://montanalegalservices.org",
        description: "Free civil legal assistance for low-income Montanans",
      },
    ],
  },
  NE: {
    stateCode: "NE",
    stateName: "Nebraska",
    filingFee: "$50–$158",
    probationFee: "$20–$50/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $25,000",
    surcharges: "Crime victim surcharge and court costs add $100–$300 per case",
    waiverForm: "Application to Proceed In Forma Pauperis (Form CC 6:3.1)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid of Nebraska",
        url: "https://legalaidofnebraska.org",
        description: "Free civil legal services for qualifying Nebraskans",
      },
    ],
  },
  NV: {
    stateCode: "NV",
    stateName: "Nevada",
    filingFee: "$50–$300",
    probationFee: "$30–$100/month",
    publicDefenderFee: "$0–$50 (reimbursement ordered at sentencing)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $50,000",
    surcharges: "Administrative assessments add ~108% on base misdemeanor fines",
    waiverForm: "Motion to Proceed In Forma Pauperis (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Nevada Legal Services",
        url: "https://nlslaw.net",
        description: "Free civil legal aid for low-income Nevadans",
      },
    ],
  },
  NH: {
    stateCode: "NH",
    stateName: "New Hampshire",
    filingFee: "$30–$175",
    probationFee: "$40/month (supervision fee)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $2,000 · Felony: up to $4,000",
    surcharges: "Victim offender dialogue, victim compensation add $25–$100",
    waiverForm: "Petition for Waiver of Filing Fees (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "New Hampshire Legal Assistance",
        url: "https://www.nhla.org",
        description: "Free civil legal aid for low-income New Hampshire residents",
      },
    ],
  },
  NJ: {
    stateCode: "NJ",
    stateName: "New Jersey",
    filingFee: "$30–$250",
    probationFee: "$0–$25/month",
    publicDefenderFee: "$0–$200 (income-based contribution)",
    fineRange: "Disorderly persons: up to $1,000 · Indictable: up to $200,000",
    surcharges: "Victim Crime Compensation adds $30–$1,000; VCCB surcharge per offense",
    waiverForm: "Application for Waiver of Filing Fees (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Services of New Jersey",
        url: "https://www.lsnj.org",
        description: "Free civil legal aid and law-line for low-income New Jerseyans",
      },
    ],
  },
  NM: {
    stateCode: "NM",
    stateName: "New Mexico",
    filingFee: "$50–$200",
    probationFee: "$0–$50/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $5,000",
    surcharges: "Crime victim reparation fund adds $100–$1,000 per conviction",
    waiverForm: "Motion to Proceed IFP / Fee Waiver — 4-982 NMRA",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "New Mexico Legal Aid",
        url: "https://www.nmlegalaid.org",
        description: "Free civil legal services for low-income New Mexicans",
      },
    ],
  },
  NY: {
    stateCode: "NY",
    stateName: "New York",
    filingFee: "$30–$400",
    probationFee: "$0 (supervision fees eliminated statewide)",
    publicDefenderFee: "$0 (application fees eliminated)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $30,000",
    surcharges: "Mandatory surcharges add $175–$375 per conviction automatically",
    waiverForm: "Poor Person Relief Application (CPLR § 1101) — ask court clerk",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid Society of New York",
        url: "https://legalaidnyc.org",
        description: "Comprehensive legal aid including criminal and civil matters for New Yorkers",
      },
      {
        name: "Empire Justice Center",
        url: "https://empirejustice.org",
        description: "Free civil legal aid and policy advocacy for low-income New Yorkers",
      },
    ],
  },
  NC: {
    stateCode: "NC",
    stateName: "North Carolina",
    filingFee: "$60–$250",
    probationFee: "$40/month (supervision fee)",
    publicDefenderFee: "$60 application fee (waivable)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: no specific statutory cap",
    surcharges: "Various court costs add $180–$250 per criminal case",
    waiverForm: "Affidavit of Indigency (AOC-CR-226)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid of North Carolina",
        url: "https://www.legalaidnc.org",
        description: "Free civil legal services for low-income North Carolinians",
      },
    ],
  },
  ND: {
    stateCode: "ND",
    stateName: "North Dakota",
    filingFee: "$50–$180",
    probationFee: "$0–$30/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $3,000 · Felony: up to $20,000",
    surcharges: "Surcharges and assessment fees add $50–$200 per case",
    waiverForm: "Petition to Proceed IFP (ask court clerk for form)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Services of North Dakota",
        url: "https://lsnd.org",
        description: "Free civil legal assistance for qualifying North Dakotans",
      },
    ],
  },
  OH: {
    stateCode: "OH",
    stateName: "Ohio",
    filingFee: "$50–$250",
    probationFee: "$25–$50/month",
    publicDefenderFee: "$0–$50 (income-based co-payment)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $20,000",
    surcharges: "Mandatory crime victims fund adds $30–$500 per conviction",
    waiverForm: "Affidavit of Indigency / Fee Waiver (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Ohio Legal Help",
        url: "https://www.ohiolegalhelp.org",
        description: "Free legal information and attorney referrals for Ohioans",
      },
    ],
  },
  OK: {
    stateCode: "OK",
    stateName: "Oklahoma",
    filingFee: "$50–$300",
    probationFee: "$40–$60/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $10,000 · Felony: up to $25,000",
    surcharges: "Multiple state fund surcharges add 100–200% on base fines",
    waiverForm: "Affidavit of Pauper / Fee Deferral (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid Services of Oklahoma",
        url: "https://legalaidok.org",
        description: "Free civil legal assistance for low-income Oklahomans",
      },
    ],
  },
  OR: {
    stateCode: "OR",
    stateName: "Oregon",
    filingFee: "$50–$252",
    probationFee: "$0–$75/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $6,250 · Felony: up to $500,000",
    surcharges: "Assessment and surcharges add 20–50% on base fines",
    waiverForm: "Request for Waiver of Filing Fees — ORS 21.685 (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Oregon Law Center",
        url: "https://oregonlawcenter.org",
        description: "Free civil legal services for low-income rural Oregonians",
      },
    ],
  },
  PA: {
    stateCode: "PA",
    stateName: "Pennsylvania",
    filingFee: "$50–$300",
    probationFee: "$25–$100/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $25,000 · Felony: up to $25,000",
    surcharges: "Court costs, access-to-justice fee, and victim comp add $200–$500",
    waiverForm: "Petition to Proceed In Forma Pauperis (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Community Legal Services (PA)",
        url: "https://clsphila.org",
        description: "Free civil legal aid for low-income Philadelphia residents",
      },
      {
        name: "Pennsylvania Legal Aid Network",
        url: "https://palawhelp.org",
        description: "Statewide network of free legal services for qualifying Pennsylvanians",
      },
    ],
  },
  RI: {
    stateCode: "RI",
    stateName: "Rhode Island",
    filingFee: "$50–$200",
    probationFee: "$0 (supervision fees eliminated statewide)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $100,000",
    surcharges: "Victim compensation surcharge adds $50–$500 per conviction",
    waiverForm: "Motion to Proceed IFP (ask court clerk for local form)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Rhode Island Legal Services",
        url: "https://www.rils.org",
        description: "Free civil legal aid for low-income Rhode Islanders",
      },
    ],
  },
  SC: {
    stateCode: "SC",
    stateName: "South Carolina",
    filingFee: "$50–$150",
    probationFee: "$30–$50/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $100,000",
    surcharges: "State surcharges add 107.5% on base fines",
    waiverForm: "Affidavit of Indigence (SCCA/50B)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "South Carolina Legal Services",
        url: "https://www.sclegal.org",
        description: "Free civil legal help for qualifying South Carolinians",
      },
    ],
  },
  SD: {
    stateCode: "SD",
    stateName: "South Dakota",
    filingFee: "$30–$175",
    probationFee: "$30–$50/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $4,000 · Felony: up to $4,000",
    surcharges: "Court costs and surcharges add $75–$200 per criminal case",
    waiverForm: "Petition to Proceed In Forma Pauperis (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "East River Legal Services",
        url: "https://www.erlservices.org",
        description: "Free civil legal aid for low-income eastern South Dakota residents",
      },
    ],
  },
  TN: {
    stateCode: "TN",
    stateName: "Tennessee",
    filingFee: "$50–$300",
    probationFee: "$35–$65/month (charged by private probation companies in many counties)",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $2,500 · Felony: up to $50,000",
    surcharges: "Multiple fund surcharges add 100–200% on base fines",
    waiverForm: "Affidavit of Indigency (AO-210 form)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid Society of Middle Tennessee",
        url: "https://las.org",
        description: "Free civil legal services for low-income Tennesseans",
      },
    ],
  },
  TX: {
    stateCode: "TX",
    stateName: "Texas",
    filingFee: "$60–$350",
    probationFee: "$25–$60/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $4,000 · Felony: up to $10,000",
    surcharges: "State and local surcharges add 100–200% on base fines; county costs vary",
    waiverForm: "Affidavit of Indigence (Form 20-101 or ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Texas RioGrande Legal Aid",
        url: "https://www.trla.org",
        description: "Free civil legal aid for low-income Texans in west and south Texas",
      },
      {
        name: "Lone Star Legal Aid",
        url: "https://lonestarlegal.blog",
        description: "Free civil legal services for qualifying Texans in eastern/central regions",
      },
    ],
  },
  UT: {
    stateCode: "UT",
    stateName: "Utah",
    filingFee: "$70–$375",
    probationFee: "$30–$50/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $2,500 · Felony: up to $10,000",
    surcharges: "Surcharges and assessments add 50–100% on base fines",
    waiverForm: "Motion to Waive Fees (UCRP 4-202.04)",
    waiverIncome: "Income ≤150% federal poverty level",
    assistanceOrgs: [
      {
        name: "Utah Legal Services",
        url: "https://www.utahlegalservices.org",
        description: "Free civil legal aid for low-income Utahns",
      },
    ],
  },
  VT: {
    stateCode: "VT",
    stateName: "Vermont",
    filingFee: "$30–$275",
    probationFee: "$0 (supervision fees eliminated)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $2,000 · Felony: up to $10,000",
    surcharges: "Surcharge adds $50–$300 per criminal case",
    waiverForm: "Application to Waive Filing Fees (Form 100.00)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Vermont Legal Aid",
        url: "https://www.vtlegalaid.org",
        description: "Free civil legal assistance for low-income Vermonters",
      },
    ],
  },
  VA: {
    stateCode: "VA",
    stateName: "Virginia",
    filingFee: "$50–$300",
    probationFee: "$30–$50/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $2,500 · Felony: up to $100,000",
    surcharges: "Fine collection fees and processing surcharges add 10–20%",
    waiverForm: "Affidavit of Indigency (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Virginia Legal Aid Society",
        url: "https://www.vlas.org",
        description: "Free civil legal services for low-income Virginians in central/western areas",
      },
      {
        name: "Legal Aid Justice Center",
        url: "https://www.justice4all.org",
        description: "Free legal aid fighting poverty and injustice across Virginia",
      },
    ],
  },
  WA: {
    stateCode: "WA",
    stateName: "Washington",
    filingFee: "$50–$400",
    probationFee: "$0–$50/month",
    publicDefenderFee: "$0 (no application fee statewide)",
    fineRange: "Misdemeanor: up to $5,000 · Felony: up to $50,000",
    surcharges: "Victim penalty assessment, filing surcharge add $500–$1,000+",
    waiverForm: "Petition and Order for Waiver of Fees — GR 34",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Northwest Justice Project",
        url: "https://nwjustice.org",
        description: "Free civil legal aid for low-income Washingtonians",
      },
    ],
  },
  WV: {
    stateCode: "WV",
    stateName: "West Virginia",
    filingFee: "$30–$200",
    probationFee: "$30–$60/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $500 · Felony: up to $25,000",
    surcharges: "Courthouse improvement fees and surcharges add $100–$200 per case",
    waiverForm: "Petition to Proceed as an Indigent Person (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Legal Aid of West Virginia",
        url: "https://legalaidwv.org",
        description: "Free civil legal services for low-income West Virginians",
      },
    ],
  },
  WI: {
    stateCode: "WI",
    stateName: "Wisconsin",
    filingFee: "$50–$500",
    probationFee: "$0–$60/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $10,000 · Felony: up to $100,000",
    surcharges: "Crime victim surcharge and court costs add $67–$250 per case",
    waiverForm: "Request to Waive Court Filing Fees (GF-26)",
    waiverIncome: "Income ≤200% federal poverty level",
    assistanceOrgs: [
      {
        name: "Wisconsin Legal Aid",
        url: "https://www.wisconsinlegalaid.org",
        description: "Free civil legal services directory for Wisconsinites",
      },
    ],
  },
  WY: {
    stateCode: "WY",
    stateName: "Wyoming",
    filingFee: "$30–$180",
    probationFee: "$0–$30/month",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $750 · Felony: up to $10,000",
    surcharges: "Surcharges and assessments add $50–$200 per criminal case",
    waiverForm: "Petition to Proceed In Forma Pauperis (ask court clerk)",
    waiverIncome: "Income ≤125% federal poverty level",
    assistanceOrgs: [
      {
        name: "Wyoming Legal Services",
        url: "https://www.wyominglegalservices.org",
        description: "Free civil legal assistance for low-income Wyoming residents",
      },
    ],
  },
  DC: {
    stateCode: "DC",
    stateName: "Washington D.C.",
    filingFee: "$50–$120",
    probationFee: "$0 (supervision fees eliminated)",
    publicDefenderFee: "$0 (no application fee)",
    fineRange: "Misdemeanor: up to $1,000 · Felony: up to $250,000",
    surcharges: "Victim compensation fund surcharge adds $100–$10,000 per conviction",
    waiverForm: "In Forma Pauperis Application — Superior Court Form CIV-14",
    waiverIncome: "Income ≤200% federal poverty level",
    assistanceOrgs: [
      {
        name: "DC Law Students in Court",
        url: "https://www.dclsic.org",
        description: "Free criminal defense representation for low-income DC residents",
      },
      {
        name: "Bread for the City",
        url: "https://breadforthecity.org",
        description: "Free civil legal aid and social services for low-income DC residents",
      },
    ],
  },
};

export const ALL_STATE_CODES: string[] = Object.keys(courtFeesByState).sort();

export function getCourtFeesForState(code: string): CourtFeeProfile | null {
  return courtFeesByState[code.toUpperCase()] ?? null;
}
